version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    environment:
      POSTGRES_USER: clebsonpy
      POSTGRES_PASSWORD: 89635241
      POSTGRES_DB: odm2
    expose:
      - "5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
